### ISSUE TITLE
프로젝트를 위한 환경 세팅

### ISSUE THREAD

**Issue by 4BFC** [HSU-Likelion12-yourSide/YourSide-Front#1]
## 📣issue
프로젝트를 위해 Eslint와 prettier를 설치 및 적용한다. 이에 대한 내용은 팀 노션에 작성 후 팀원에게 공유한다.
## 🔐i&s
Eslint에 prettier를 통합 설치 하였다. npm으로 진행을 하였고 해당 npm은 아래와 같다.
```
npm install eslint-plugin-prettier@latest --save-dev
```
```
npm install eslint-config-prettier --save-dev
```
* pull로 가져온 후 전체 package들을 설치 및 적용 하기 위해선 아래와 같이 명령하면 된다.
```
npm i
```
## 📌pin
[📌Eslint&Pretter-Config](https://pyrite-condor-2fd.notion.site/Eslint-Pretter-Congif-e56c6a1086ae48eaba3ef5ab26229576?pvs=4)
## 🗓next tasks
- 팀원과 함께 협의한 파일 구조를 설정한다.
- 해당 파일마다 jsx 코드를 설정한다.
- GitHub lables와 GitHub 커밋 가이드라인을 정한다.

**Comment by 4BFC** [comment]
개발 환경 설정으로 이해 브런치를 따로 생성하지 않고 main에 직접 push를 실시 했습니다. 확인해주시고 코멘트 달아 주시면 감사하겠습니다. @N4nc2y

**Comment by ye-eun-min201** [comment]
확인 하겠습니다. 감사합니다!
